### ISSUE TITLE
You have requested a non-existent service "nelmio_api_doc.form.extension.description_form_type_extension"

### ISSUE THREAD

**Issue by andreybolonin** [sonata-project/SonataCoreBundle#223]
![fwkwxtz](https://cloud.githubusercontent.com/assets/995707/12088241/c5307288-b2d9-11e5-85be-285f1b45242f.png)

**Comment by core23** [comment]
Sure this is related to the CoreBundle? Can you give some more information?

**Comment by StudioMaX** [comment]
This issue was fixed by https://github.com/sonata-project/SonataCoreBundle/pull/222 (21 Dec 2015), but, unfortunately, the new tag with this fix was not released (latest release 2.3.10 from 27 Nov 2015). So, we need to update our composer.json dependencies to `"sonata-project/core-bundle": "dev-master"`.

**Comment by core23** [comment]
This issue should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue
